'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cosecha_Producto_TarifaEscala
    Public Property IDCosecha As Byte
    Public Property IDProducto As Byte
    Public Property Indice As Short
    Public Property HumedadExcesoInicio As Decimal
    Public Property Tipo As String
    Public Property Tarifa As Decimal

    Public Overridable Property Cosecha_Producto_Tarifa As Cosecha_Producto_Tarifa

End Class
