'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cosecha_Producto_Tarifa
    Public Property IDCosecha As Byte
    Public Property IDProducto As Byte
    Public Property Indice As Short
    Public Property IDPlanta As Nullable(Of Byte)
    Public Property IDEntidad As Nullable(Of Integer)
    Public Property IDOrigenDestino As Nullable(Of Integer)
    Public Property Nombre As String
    Public Property FechaDesde As Nullable(Of Date)
    Public Property FechaHasta As Nullable(Of Date)
    Public Property TarifaParitariaImporte As Decimal
    Public Property TarifaSecadoTipo As String
    Public Property TarifaSecadoInicialPunto As Decimal
    Public Property TarifaSecadoInicialImporte As Decimal
    Public Property TarifaSecadoPuntoExcesoImporte As Decimal
    Public Property TarifaSecadoHumedadBase As Nullable(Of Decimal)
    Public Property TarifaSecadoHumedadMargenLibre As Nullable(Of Decimal)
    Public Property TarifaSecadoHumedadRedondeoPuntoTipo As String
    Public Property TarifaZarandeoImporte As Decimal
    Public Property TarifaFumigadoImporte As Decimal
    Public Property TarifaMezclaImporte As Decimal
    Public Property AlmacenajeTipo As String
    Public Property AlmacenajeDiaGracia As Nullable(Of Short)
    Public Property AlmacenajeInicio As Nullable(Of Date)
    Public Property AlmacenajePorcentajeMensual As Decimal

    Public Overridable Property Cosecha As Cosecha
    Public Overridable Property Producto As Producto
    Public Overridable Property Cosecha_Producto_TarifaEscala As ICollection(Of Cosecha_Producto_TarifaEscala) = New HashSet(Of Cosecha_Producto_TarifaEscala)
    Public Overridable Property Planta As Planta

End Class
