'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Entidad_Producto_Planta
    Public Property IDEntidad As Integer
    Public Property IDProducto As Byte
    Public Property IDPlanta As Byte
    Public Property TipoEntrada As Boolean
    Public Property TipoSalida As Boolean
    Public Property TipoNinguno As Boolean

    Public Overridable Property Entidad As Entidad
    Public Overridable Property Producto_Planta As Producto_Planta

End Class
