'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Entidad_Planta
    Public Property IDEntidad As Integer
    Public Property IDPlanta As Byte
    Public Property Tipo As String
    Public Property UsoFrecuente As Boolean
    Public Property UltimoUso As Date

    Public Overridable Property Entidad As Entidad
    Public Overridable Property Planta As Planta

End Class
