'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Localidad
    Public Property IDProvincia As Byte
    Public Property IDLocalidad As Short
    Public Property Nombre As String
    Public Property CodigoPostal As String

    Public Overridable Property OrigenesDestinos As ICollection(Of OrigenDestino) = New HashSet(Of OrigenDestino)
    Public Overridable Property Provincia As Provincia

End Class
