'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrigenDestino
    Public Property IDOrigenDestino As Integer
    Public Property Nombre As String
    Public Property Domicilio As String
    Public Property IDProvincia As Nullable(Of Byte)
    Public Property IDLocalidad As Nullable(Of Short)
    Public Property CodigoPostal As String
    Public Property UbicacionLatitud As Nullable(Of Decimal)
    Public Property UbicacionLongitud As Nullable(Of Decimal)
    Public Property Notas As String
    Public Property EsActivo As Boolean
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property Entidades_OrigenesDestinos As ICollection(Of Entidad_OrigenDestino) = New HashSet(Of Entidad_OrigenDestino)
    Public Overridable Property Localidad As Localidad
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario
    Public Overridable Property Cosecha_Producto_Tarifas As ICollection(Of Cosecha_Producto_Tarifa) = New HashSet(Of Cosecha_Producto_Tarifa)
    Public Overridable Property PesadasDestino As ICollection(Of Pesada) = New HashSet(Of Pesada)
    Public Overridable Property PesadasOrigen As ICollection(Of Pesada) = New HashSet(Of Pesada)

End Class
