'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Parametro
    Public Property IDParametro As String
    Public Property Texto As String
    Public Property NumeroEntero As Nullable(Of Integer)
    Public Property NumeroDecimal As Nullable(Of Decimal)
    Public Property Moneda As Nullable(Of Decimal)
    Public Property FechaHora As Nullable(Of Date)
    Public Property SiNo As Nullable(Of Boolean)
    Public Property Notas As String

End Class
