Module Parametros
    ' APLICACIÓN
    Friend Const APPLICATION_DATABASE_GUID As String = "APPLICATION_DATABASE_GUID"
    Friend Const LICENSE_COMPANY_NAME As String = "LICENSE_COMPANY_NAME"

    Friend Const USER_USERNAME_MINIMUM_LENGHT As String = "USER_USERNAME_MINIMUM_LENGHT"
    Friend Const USER_PASSWORD_MINIMUM_LENGHT As String = "USER_PASSWORD_MINIMUM_LENGHT"
    Friend Const USER_PASSWORD_SECURE_REQUIRED As String = "USER_PASSWORD_SECURE_REQUIRED"

    ' VALORES PREDETERMINADOS
    Friend Const DEFAULT_PROVINCIA_ID As String = "DEFAULT_PROVINCIA_ID"
    Friend Const DEFAULT_LOCALIDAD_ID As String = "DEFAULT_LOCALIDAD_ID"
    Friend Const DEFAULT_CODIGOPOSTAL As String = "DEFAULT_CODIGOPOSTAL"

    ' PESADAS
    Friend Const PESADA_FECHA_INICIOACTUAL_ANTERIOR_DIFERENCIAMAXIMA_DIAS As String = "PESADA_FECHA_INICIOACTUAL_ANTERIOR_DIFERENCIAMAXIMA_DIAS"
    Friend Const PESADA_FECHA_INICIOFIN_DIFERENCIAMAXIMA_DIAS As String = "PESADA_FECHA_INICIOFIN_DIFERENCIAMAXIMA_DIAS"
    Friend Const PESADA_HORA_INICIOACTUAL_DIFERENCIAMAXIMA_MINUTOS As String = "PESADA_HORA_INICIOACTUAL_DIFERENCIAMAXIMA_MINUTOS"

    ' REPORTES
    Friend Const REPORTE_ID_PERSONA_FICHA As String = "REPORTE_ID_PERSONA_FICHA"
End Module
