'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pesada_Analisis
    Public Property IDPesada As Integer
    Public Property Humedad As Nullable(Of Decimal)
    Public Property Zaranda As Nullable(Of Decimal)
    Public Property GranoVerde As Nullable(Of Decimal)
    Public Property GranoDaniado As Nullable(Of Decimal)
    Public Property PesoHectolitrico As Nullable(Of Decimal)
    Public Property Gluten As Nullable(Of Decimal)
    Public Property Fumigado As Nullable(Of Boolean)
    Public Property MermaVolatilKilogramo As Nullable(Of Integer)
    Public Property MermaHumedadPorcentaje As Nullable(Of Decimal)
    Public Property MermaHumedadKilogramo As Nullable(Of Integer)
    Public Property MermaZarandaKilogramo As Nullable(Of Integer)

    Public Overridable Property Pesada As Pesada

End Class
