'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pesada
    Public Property IDPesada As Integer
    Public Property FechaHoraInicio As Date
    Public Property FechaHoraFin As Nullable(Of Date)
    Public Property ComprobanteNumero As String
    Public Property ComprobanteNumeroTercero As String
    Public Property IDPlanta As Nullable(Of Byte)
    Public Property IDProducto As Byte
    Public Property IDCosecha As Nullable(Of Byte)
    Public Property Tipo As String
    Public Property TipoNombre As String
    Public Property Titular_IDEntidad As Integer
    Public Property IDOrigenDestino As Nullable(Of Integer)
    Public Property Transportista_IDEntidad As Nullable(Of Integer)
    Public Property Chofer_IDEntidad As Nullable(Of Integer)
    Public Property IDCamion As Nullable(Of Byte)
    Public Property Kilometro As Nullable(Of Short)
    Public Property KilogramoBruto As Nullable(Of Integer)
    Public Property KilogramoTara As Nullable(Of Integer)
    Public Property KilogramoNeto As Nullable(Of Integer)
    Public Property KilogramoFinal As Nullable(Of Integer)
    Public Property Notas As String
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property Cosecha As Cosecha
    Public Overridable Property EntidadChofer As Entidad
    Public Overridable Property EntidadTitular As Entidad
    Public Overridable Property EntidadTransportista As Entidad
    Public Overridable Property Pesada_Acondicionamiento As Pesada_Acondicionamiento
    Public Overridable Property Pesada_Analisis As Pesada_Analisis
    Public Overridable Property Pesada_Otro As Pesada_Otro
    Public Overridable Property Planta As Planta
    Public Overridable Property Producto As Producto
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario
    Public Overridable Property Camion As Camion
    Public Overridable Property Camion1 As Camion

End Class
