'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pesada_Otro
    Public Property IDPesada As Integer
    Public Property Producto_Nombre As String
    Public Property Titular_Nombre As String
    Public Property OrigenDestino_Nombre As String
    Public Property Transportista_Nombre As String
    Public Property Transportista_CUIT As String
    Public Property Chofer_Nombre As String
    Public Property Chofer_CUIT_CUIL As String
    Public Property Camion_DominioChasis As String
    Public Property Camion_DominioAcoplado As String

    Public Overridable Property Pesada As Pesada

End Class
