'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pesada_Acondicionamiento
    Public Property IDPesada As Integer
    Public Property TarifaIndice As Short
    Public Property ParitariaTarifa As Decimal
    Public Property ParitariaImporte As Decimal
    Public Property SecadoTarifa As Decimal
    Public Property SecadoImporte As Decimal
    Public Property HumedadExcesoReal As Decimal
    Public Property HumedadExcesoCalculo As Decimal
    Public Property SecadoExcesoTarifa As Decimal
    Public Property SecadoExcesoImporte As Decimal
    Public Property ZarandeoTarifa As Decimal
    Public Property ZarandeoImporte As Decimal
    Public Property FumigadoTarifa As Decimal
    Public Property FumigadoImporte As Decimal
    Public Property MezclaTarifa As Decimal
    Public Property MezclaImporte As Decimal
    Public Property ImporteTotal As Decimal
    Public Property FechaLiquidacion As Nullable(Of Date)

    Public Overridable Property Pesada As Pesada

End Class
