'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Planta
    Public Property IDPlanta As Byte
    Public Property Nombre As String
    Public Property AplicaMermaVolatil As Boolean
    Public Property EsActivo As Boolean
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property Cosecha_Producto_Tarifa As ICollection(Of Cosecha_Producto_Tarifa) = New HashSet(Of Cosecha_Producto_Tarifa)
    Public Overridable Property Pesada As ICollection(Of Pesada) = New HashSet(Of Pesada)
    Public Overridable Property Producto_Planta As ICollection(Of Producto_Planta) = New HashSet(Of Producto_Planta)
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario

End Class
