'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Producto_Cosecha
    Public Property IDProducto As Byte
    Public Property IDCosecha As Byte
    Public Property Inicio As Date
    Public Property Fin As Date
    Public Property EsActivo As Boolean

    Public Overridable Property Cosecha As Cosecha
    Public Overridable Property Producto As Producto

End Class
