'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ReporteParametro
    Public Property IDReporte As Short
    Public Property IDParametro As String
    Public Property Nombre As String
    Public Property Tipo As String
    Public Property Requerido As Boolean
    Public Property RequeridoLeyenda As String
    Public Property ValorPredeterminadoNumeroEntero As Nullable(Of Integer)
    Public Property ValorPredeterminadoNumeroDecimal As Nullable(Of Decimal)
    Public Property ValorPredeterminadoMoneda As Nullable(Of Decimal)
    Public Property ValorPredeterminadoFechaHora As Nullable(Of Date)
    Public Property ValorPredeterminadoSiNo As Nullable(Of Boolean)
    Public Property Orden As Nullable(Of Byte)

    Public Overridable Property Reporte As Reporte

End Class
