'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property IDUsuario As Short
    Public Property Nombre As String
    Public Property Descripcion As String
    Public Property Password As String
    Public Property Genero As String
    Public Property IDUsuarioGrupo As Byte
    Public Property EsActivo As Boolean
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property CamionesCreados As ICollection(Of Camion) = New HashSet(Of Camion)
    Public Overridable Property CamionesModificados As ICollection(Of Camion) = New HashSet(Of Camion)
    Public Overridable Property CosechasCreadas As ICollection(Of Cosecha) = New HashSet(Of Cosecha)
    Public Overridable Property CosechasModificadas As ICollection(Of Cosecha) = New HashSet(Of Cosecha)
    Public Overridable Property EntidadesCreadas As ICollection(Of Entidad) = New HashSet(Of Entidad)
    Public Overridable Property EntidadesModificadas As ICollection(Of Entidad) = New HashSet(Of Entidad)
    Public Overridable Property Entidades_OrigenesDestinosCreados As ICollection(Of Entidad_OrigenDestino) = New HashSet(Of Entidad_OrigenDestino)
    Public Overridable Property Entidades_OrigenesDestinosModificados As ICollection(Of Entidad_OrigenDestino) = New HashSet(Of Entidad_OrigenDestino)
    Public Overridable Property OrigenesDestinosCreados As ICollection(Of OrigenDestino) = New HashSet(Of OrigenDestino)
    Public Overridable Property OrigenesDestinosModificados As ICollection(Of OrigenDestino) = New HashSet(Of OrigenDestino)
    Public Overridable Property PesadasCreadas As ICollection(Of Pesada) = New HashSet(Of Pesada)
    Public Overridable Property PesadasModificadas As ICollection(Of Pesada) = New HashSet(Of Pesada)
    Public Overridable Property PlantasCreadas As ICollection(Of Planta) = New HashSet(Of Planta)
    Public Overridable Property PlantasModificadas As ICollection(Of Planta) = New HashSet(Of Planta)
    Public Overridable Property ProductosCreados As ICollection(Of Producto) = New HashSet(Of Producto)
    Public Overridable Property ProductosModficados As ICollection(Of Producto) = New HashSet(Of Producto)
    Public Overridable Property UsuariosGruposCreados As ICollection(Of UsuarioGrupo) = New HashSet(Of UsuarioGrupo)
    Public Overridable Property UsuariosGruposModificados As ICollection(Of UsuarioGrupo) = New HashSet(Of UsuarioGrupo)
    Public Overridable Property UsuarioGrupo As UsuarioGrupo
    Public Overridable Property PlantasDepositosCreados As ICollection(Of PlantaDeposito) = New HashSet(Of PlantaDeposito)
    Public Overridable Property PlantasDepositos As ICollection(Of PlantaDeposito) = New HashSet(Of PlantaDeposito)
    Public Overridable Property UsuariosCreados As ICollection(Of Usuario) = New HashSet(Of Usuario)
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuariosModificados As ICollection(Of Usuario) = New HashSet(Of Usuario)
    Public Overridable Property UsuarioModificacion As Usuario

End Class
