'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_APPLICATION_ICON_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_APPLICATION_ICON_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_CALENDAR_NEXT_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_CALENDAR_NEXT_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_CALENDAR_PREVIOUS_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_CALENDAR_PREVIOUS_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_CALENDAR_TODAY_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_CALENDAR_TODAY_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_CARDONERSISTEMAS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_CARDONERSISTEMAS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_CLOSE_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_CLOSE_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_CLOSE_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_CLOSE_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_INICIO_SESION_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_INICIO_SESION_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_ITEM_ADD_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_ITEM_ADD_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_ITEM_COPY_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_ITEM_COPY_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_ITEM_DELETE_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_ITEM_DELETE_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_ITEM_EDIT_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_ITEM_EDIT_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_MENU_WINDOW_CLOSE_ALL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_MENU_WINDOW_CLOSE_ALL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_MENU_WINDOW_FIT_SIZE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_MENU_WINDOW_FIT_SIZE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_MENU_WINDOW_TILE_HORIZONTALLY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_MENU_WINDOW_TILE_HORIZONTALLY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_MENU_WINDOW_TILE_VERTICALLY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_MENU_WINDOW_TILE_VERTICALLY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_MOVE_NEXT_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_MOVE_NEXT_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_MOVE_PREVIOUS_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_MOVE_PREVIOUS_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_PERSONA_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_PERSONA_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_PESADAS_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_PESADAS_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_PRINT_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_PRINT_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_PRINT_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_PRINT_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_PRINT_PREVIEW_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_PRINT_PREVIEW_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_PRINT_PREVIEW_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_PRINT_PREVIEW_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_REPORTES_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_REPORTES_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_SCALE_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_SCALE_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_SEARCH_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_SEARCH_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_SPLASH_SCREEN_BACKGROUND() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_SPLASH_SCREEN_BACKGROUND", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_TABLAS_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_TABLAS_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_USUARIO_HOMBRE_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_USUARIO_HOMBRE_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_USUARIO_HOMBRE_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_USUARIO_HOMBRE_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_USUARIO_MUJER_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_USUARIO_MUJER_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMAGE_USUARIO_MUJER_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_USUARIO_MUJER_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAceptar32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAceptar32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageCancelar32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageCancelar32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageDatabaseLoginInfo48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageDatabaseLoginInfo48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageDatabaseSelect48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageDatabaseSelect48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error al guardar los cambios en la Base de Datos..
        '''</summary>
        Friend ReadOnly Property STRING_ERROR_SAVING_CHANGES() As String
            Get
                Return ResourceManager.GetString("STRING_ERROR_SAVING_CHANGES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Femenino.
        '''</summary>
        Friend ReadOnly Property STRING_GENERO_FEMENINO() As String
            Get
                Return ResourceManager.GetString("STRING_GENERO_FEMENINO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Masculino.
        '''</summary>
        Friend ReadOnly Property STRING_GENERO_MASCULINO() As String
            Get
                Return ResourceManager.GetString("STRING_GENERO_MASCULINO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Todas».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_ALL_FEMALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_ALL_FEMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Todos».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_ALL_MALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_ALL_MALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Completa».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_COMPLETE_FEMALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_COMPLETE_FEMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Completo».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_COMPLETE_MALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_COMPLETE_MALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Vacía».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_EMPTY_FEMALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_EMPTY_FEMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Vacío».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_EMPTY_MALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_EMPTY_MALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_END_CHAR() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_END_CHAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Nuevo».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NEW_MALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NEW_MALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ----------.
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NONE_CHARS10() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NONE_CHARS10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --.
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NONE_CHARS2() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NONE_CHARS2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --------------------.
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NONE_CHARS20() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NONE_CHARS20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -----.
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NONE_CHARS5() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NONE_CHARS5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Ninguno».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NONE_FEMALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NONE_FEMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Ninguna».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NONE_MALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NONE_MALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «No especifica».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_NOT_SPECIFIED() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_NOT_SPECIFIED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Otra».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_OTHER_FEMALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_OTHER_FEMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «Otro».
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_OTHER_MALE() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_OTHER_MALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to «.
        '''</summary>
        Friend ReadOnly Property STRING_ITEM_START_CHAR() As String
            Get
                Return ResourceManager.GetString("STRING_ITEM_START_CHAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend ReadOnly Property STRING_NO() As String
            Get
                Return ResourceManager.GetString("STRING_NO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No tiene autorización para realizar esta acción..
        '''</summary>
        Friend ReadOnly Property STRING_PERMISO_MENSAJE() As String
            Get
                Return ResourceManager.GetString("STRING_PERMISO_MENSAJE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sí.
        '''</summary>
        Friend ReadOnly Property STRING_YES() As String
            Get
                Return ResourceManager.GetString("STRING_YES", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
